language: "zh"

pipeline:
  - name: MitieNLP
    model: "/Users/zhangzhen/gitRepository/rasa/data/total_word_feature_extractor_zh.dat"
  - name: JiebaTokenizer
  - name: "examples.luckinbot.extractor.LuckinEntityExtractor"
  - name: DucklingHTTPExtractor
    url: "http://0.0.0.0:8000"
  - name: MitieFeaturizer
  - name: SklearnIntentClassifier

policies:
  - name: FormPolicy
  - name: MemoizationPolicy
  - name: EmbeddingPolicy
    epochs: 30
    max_history: 3
  - name: FallbackPolicy
    nlu_threshold: 0.6
